### ISSUE TITLE
Separating subnet (source) and port definitions

### ISSUE THREAD

**Issue by asoltesz** [vitobotta/ansible-firewalld-role#1]
Currently, I get this error on task "Configure private network: 2378-2380/tcp": 

"can only operate on port, service, rich_rule, masquerade, icmp_block, icmp_block_inversion, interface or source at once"

Looks like "source" and "port" cannot be used together anymore.

An attempted fix is in [this commit](https://github.com/asoltesz/ansible-firewalld-role/commit/7ad2f63c43480a04c84cbc5a2ae5b781484f897f).

**Comment by vitobotta** [comment]
I've merged the related PR.
